language: python
os:
- linux
python:
- '3.4'
addons:
  apt:
    packages:
    - lmodern
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texlive-xetex
    - texlive-extra-utils
install:
- pip install -r requirements.txt
- sudo ln -s /usr/share/i18n/SUPPORTED /var/lib/locales/supported.d/all
- sudo locale-gen cs_CZ.UTF-8
script:
- make
before_deploy:
- make -C output
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: output
  on:
    branch: master
env:
  global:
  - secure: lZxQ9+kfyqzvmPvxLPv6FvTwGbOrAdek3tU/05me30vVb2VA8mvBj8+ELQjWvuuNEtUJ6NSAIDn0o2wntoy5uK8cA7jPMOCMUH3H1oHNxiAjJb9Pj0l14RZJ6HxVQCdTXDDlcV99AkkD5YbFNhNcLsiQO+o7FLIvXpEoS1J0HsY=
  - secure: CvGQvGyks7jQLk4LbhgyQkm+O3ycoW/Qq64Yy5BXBrHwLgeUAPgY2j10pwSlWAZ8UO37cChpe+itD0LAGJqeRAlp1KhtUgtslVqJWEZQDRyZ8HPjT+2SWJVZtFTCYr/4/fzx2Vsjl6el7I3cGLzyUbuQM9h168pxYEINePTD1As=
  - secure: adf0i/D3Hpn8JQcof+P4V6sw/IPj1K5divUcew0X5e2dsNTr5RfIR1d9m36ikCjywJv/5SiPulxTAF2yDa9riS3AlwKSjCSBqUHCL0JjBk8N6gXkbFmBW0bqmCCoMEvLifI0R+PsqMwrNopWEVO+dArzNh+FAfzhmRtY3zx7j/c=
