language: python
os:
  - linux
python:
  - "3.3"
  - "3.4"
install:
  - "pip install -r requirements.txt"
  - "sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-xetex"
  - "sudo ln -s /usr/share/i18n/SUPPORTED /var/lib/locales/supported.d/all"
  - "sudo locale-gen"
script:
  - "snakemake -p -s Snakefile.test"
  - "snakemake -p -s Snakefile.TP2011"
  - "snakemake -p -s Snakefile.TP2012"
  - "snakemake -p -s Snakefile.TP2013"
  - "snakemake -p -s Snakefile.AllSongs"
  
